export const T = {
  appName: "Stream for All",
  popup: {
    tagline: "Compartilhamento de tela privado para a sua turma — crie ou entre em uma sala em segundos.",
    start: "Começar transmissão"
  },
  onboarding: {
    nickname: "Apelido",
    nicknamePlaceholder: "ex: leo",
    hey: (name) => `Olá, ${name}`,
    choiceSubtitle: "Entre na sala de um amigo ou crie a sua.",
    hostRoom: "Criar uma sala",
    joinRoom: "Entrar com código",
    back: "Voltar",
    joinTitle: "Entrar com código",
    joinSubtitle: "Cole o código da sala que um amigo enviou.",
    roomCode: "Código da sala",
    join: "Entrar",
    badCode: "Esse código não parece certo.",
    hostTitle: "Quase lá",
    hostSubtitle: "Envie este link para os seus amigos entrarem.",
    copyLink: "Copiar link de convite",
    linkNotOpening: "Link não abre?",
    copyCode: "Copiar código",
    copied: "Copiado ✓",
    createRoom: "Criar sala"
  },
  room: {
    liveNow: "Ao vivo agora",
    empty: "Ninguém está transmitindo ainda.",
    shareScreen: "Compartilhar tela",
    stopSharing: "Parar de compartilhar",
    waiting: "Aguardando aprovação...",
    you: (name) => `${name} (você)`,
    members: "Membros",
    requests: "Pedidos para entrar",
    noRequests: "Nenhum pedido pendente.",
    approve: "Aprovar",
    clickToWatch: "Clique para assistir",
    stopWatching: "Clique para parar de assistir",
    live: "Ao vivo",
    host: "Anfitrião",
    ping: (ms) => `${ms} ms`,
    sound: "Som",
    copyInvite: "Copiar link de convite",
    inviteCopied: "Link de convite copiado",
    framerate: "Taxa de quadros",
    resolution: "Resolução",
    native: "Nativa",
    fps: (n) => `${n} fps`,
    roomSettings: "Configurações da sala",
    streamSettings: "Configurações da transmissão",
    openInWindow: "Abrir em uma janela separada",
    close: "Fechar",
    signalingFailed: "Falha ao iniciar a sinalização: ",
    status: (total, online) =>
      `${total} ${total === 1 ? "membro" : "membros"} · ${online} online com você`
  }
};
